### ISSUE TITLE
All of my errors I encountered thus far

### ISSUE THREAD

**Issue by Gamerzcrafted** [FreeAgarBots/v3#1]
```
FreeAgarBots v2.5\FreeAgarBots v2.5\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of reserved fields must be empty
    at WebSocket.onError (C:\FileLocation\node_modules\ws\lib\WebSocket.js:426:16)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (C:\FileLocation\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (C:\FileLocation\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (C:\FileLocation\node_modules\ws\lib\Receiver.js:195:12)
    at Receiver.add (C:\FileLocation\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (C:\FileLocation\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

C:\FileLocation>Pause
```

```
Bot_221: Packet error detected for packet: 10 00 00 85 dd 15 00 c0 f9 ff ff e8 0e 00 00 99 00 ff 07 d6 04 25 66 6c 79 00 22 00 22 26 20 00 23 26 20 00 21 27 20 00 21 27 20 00 23 26 20 00 22 26 22 00 00 00 0c eb 15 00 5d f9 ff ff ee 11 00 00 2f 00 ff 07 68 00 00 00 20 eb 15 00 38 fe ff ff d7 12 00 00 95 01 e2 ff 07 00 00 82 7e 00 83 10 00 00 85 dd 15 00 c4 f9 ff ff f0 0e 00 00 99 00 ff 07 d6 00 00 00 0c eb 15 00 5d f9 ff ff ee 11 00 00 2f 00 ff 07 68 00 00 00 20 eb 15 00 3a fe ff ff d2 12 00 00 95 01 e2 ff 07 00 00 00 6c f8
Bot_221: Crash will be prevented, bot will be disconnected
C:\FileLocation\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of reserved fields must be empty
    at WebSocket.onError (C:\FileLocation\node_modules\ws\lib\WebSocket.js:426:16)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (C:\FileLocation\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (C:\FileLocation\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (C:\FileLocation\node_modules\ws\lib\Receiver.js:195:12)
    at Receiver.add (C:\FileLocation\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (C:\FileLocation\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

C:\FileLocation>Pause
```

**Comment by ghost** [comment]
same

**Comment by easyrider81** [comment]
comment out line 426 in websocket.js

location for OP:
C:\FileLocation\node_modules\ws\lib\WebSocket.js

**Comment by Agarian** [comment]
which websocket.js??
